name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: Oliver9105
          outputs: |
            dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
